script/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// All installer route are here
Route::get('install','Installer\InstallerController@install')->name('install');
Route::get('install/purchase','Installer\InstallerController@purchase')->name('purchase');
Route::post('install/purchase_check','Installer\InstallerController@purchase_check')->name('purchase_check');
Route::get('install/check','Installer\InstallerController@check')->name('install.check');
Route::get('install/info','Installer\InstallerController@info')->name('install.info');
Route::get('install/migrate','Installer\InstallerController@migrate')->name('install.migrate');
Route::get('install/seed','Installer\InstallerController@seed')->name('install.seed');
Route::post('install/store','Installer\InstallerController@send');
Route::get('404',function(){
	return abort(404);
})->name(404);


// // sitemap route
Route::get('/sitemap.xml', 'SettingController@sitemapView');

Route::get('locale','LocalizationController@store')->name('language.set'); 
// laravel auth routes
Auth::routes(['verify' => true]);
Route::get('/mysettings','Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
Route::post('genup','Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
Route::post('passup','Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');



Route::get('test', function(Request $request) {
    dd($request);
});
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
|
*/

//Admin settings route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){
	//dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('announcement','DashboardController@announcement')->name('announcement');
	// page resource route
	Route::resource('page','PageController');
	Route::post('pages/destroy','PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post','PostController');
	Route::post('post/destroy','PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment','CommentController');
	Route::get('/comment/disqus','CommentController@apiview')->name('dsiqus.settings');

	Route::post('blog/comments/destroy','CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}','CommentController@reply')->name('comment.reply');
	Route::resource('blog/category','CategoryController');

	Route::post('disqus','CommentController@disqus')->name('disqus.store');

	// category route
	Route::post('categorys','CategoryController@destroy')->name('categorys.destroy');
	Route::resource('settings','SettingsController');
	// menu route
	Route::resource('appearance/menu','MenuController');
	Route::post('menues/destroy','MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node','MenuController@MenuNodeStore')->name('menus.MenuNodeStore');
	//theme route 
	Route::get('appearance/theme','ThemeController@index')->name('theme.index');
	Route::get('theme/{name}','ThemeController@active')->name('theme.active');
	Route::post('theme/upload','ThemeController@upload')->name('theme.upload');
	//widget route 
	Route::get('appearance/widget','WidgetController@index')->name('widget.index');
	//themeoptions route
	Route::get('appearance/themeoptions','ThemeoptionsController@index')->name('themeoptions.index');
	//script route
	Route::resource('appearance/script','ScriptController');
	//Plugin route
	Route::get('plugin','PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}','PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}','PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload','PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo','SeoController');

	//env route
	Route::resource('setting/env','EnvController');
	Route::resource('setting/filesystem','FilesystemController');

	//performance route
	Route::resource('setting/performance','PerfomaceController');


	//general route
	Route::resource('setting/general','GensettingsController');


	//permission route
	Route::get('permission','PermissionController@index')->name('permission.index');


	//usersystem route
	Route::get('usersystem','UsersystemController@index')->name('usersystem.index');


	//information route
	Route::get('information','InformationController@index')->name('information.index');

	//permissions
	Route::resource('permission','PermissionController');

	//langauge route
	Route::resource('language','LanguageController');


	//Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');

});


/*
|--------------------------------------------------------------------------
| Store Routes
|--------------------------------------------------------------------------
|
| All Store routes are here
|
|
*/
Route::group(['as' =>'store.','prefix'=>'store','namespace'=>'Store','middleware'=>['auth','store','verified','approval']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('status','DashboardController@status')->name('status');
});


Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::resource('media','MediaController');
	Route::get('medias/json','MediaController@json')->name('medias.json');
	Route::get('media/info/{id}','MediaController@show');
	Route::post('medias/remove','MediaController@destroy')->name('medias.destroy');
	
});

// Social Login Route
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

script/resources/views/admin/page/create.blade.php
@extends('layouts.backend.app')
@section('content')
<div class="row">
	<div class="col-lg-9">      
		<div class="card">
			<div class="card-body">
				<h4>{{ __('Add new Page') }}</h4>
				<form method="post" action="{{ route('admin.page.store') }}" id="basicform">
					@csrf
					<div class="custom-form pt-20">
						@php
						$arr['title']= 'Page Title';
						$arr['id']= 'name';
						$arr['type']= 'text';
						$arr['placeholder']= 'Page Title';
						$arr['name']= 'title';
						$arr['is_required'] = true;

						echo  input($arr);

						$arr['title']= 'Meta Description';
						$arr['id']= 'excerpt';
						$arr['placeholder']= 'short description';
						$arr['name']= 'excerpt';
						$arr['is_required'] = true;

						echo  textarea($arr);

						$arrn['title']= 'Page Content';
						$arrn['name']= 'content';

						echo  textarea($arrn);
						@endphp
					</div>
				</div>
			</div>

		</div>
		<div class="col-lg-3">
			<div class="single-area">
				<div class="card">
					<div class="card-body">
						<h5>{{ __('Publish') }}</h5>
						<hr>
						<div class="btn-publish">
							<button type="submit" class="btn btn-primary col-12"><i class="fa fa-save"></i> {{ __('Save') }}</button>
						</div>
					</div>
				</div>
			</div>
			<div class="single-area">
				<div class="card sub">
				<div class="card-body">
						<h5>{{ __('Status') }}</h5>
					<hr>
					<select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="status">
							<option selected value="1">{{ __('Published') }}</option>
							<option value="2">{{ __('Draft') }}</option>

					</select>
				</div>
			</div>
		</div>
	</div>

	<input type="hidden" name="type" value="1">
	<input type="hidden"  name="post_type" value="page">
</form>
@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>

<script>
	"use strict";	
	(function ($) {
		
		
		$('.use').on('click',function(){
			$('#preview').attr('src',myradiovalue);
			$('#image').val(myradiovalue);
		});

	})(jQuery);	
	//success response will assign here
	function success(res){
		location.reload()
	}	
</script>
@endsection

script/resources/views/admin/page/edit.blade.php
@extends('layouts.backend.app')
@section('content')
<div class="row">
	<div class="col-lg-9">      
		<div class="card">
			<div class="card-body">
				<h4>{{ __('Edit Page') }}</h4>
				
				<form method="post" id="basicform" action="{{ route('admin.page.update',$info->id) }}">
					@csrf
					@method('PUT')

					<div class="custom-form pt-20">

						@php
						$arr['title']= 'Page Title';
						$arr['id']= 'name';
						$arr['type']= 'text';
						$arr['placeholder']= 'Page Title';
						$arr['name']= 'title';
						$arr['is_required'] = true;
						$arr['value'] = $info->title;

						echo  input($arr);

						$arr['title']= 'Slug';
						$arr['id']= 'slug';
						$arr['type']= 'text';
						$arr['placeholder']= 'slug';
						$arr['name']= 'slug';
						$arr['is_required'] = true;
						$arr['value'] = $info->slug;

						echo  input($arr);

						$arr['title']= 'Meta Description';
						$arr['id']= 'excerpt';
						$arr['placeholder']= 'short description';
						$arr['name']= 'excerpt';
						$arr['is_required'] = true;
						$arr['value'] = $info->excerpt->content;

						echo  textarea($arr);
						
						$arrn1['title']= 'Page Content';
						$arrn1['name']= 'content';
						$arr1['id']= 'content';
						$arr1['value'] = $info->content->content;
						
						echo  textarea($arrn1);

					
						@endphp


					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-body">
					<h4>{{ __('Search Engine Optimization') }}</h4>
					<div class="search-engine">
						<h6 class="pt-15 page-title-seo" id="seotitle">{{ $info->title }}</h6>
						<a href="#" class="text-success" id="seourl">{{ url('/').'/page/'.$info->slug }}</a>
						<p id="seodescription">{{ $info->meta->excerpt }}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-3">
			<div class="single-area">
				<div class="card">
					<div class="card-body">
						<h5>{{ __('Publish') }}</h5>
						<hr>
						<div class="btn-publish">
							<button type="submit" class="btn btn-primary col-12"><i class="fa fa-save"></i> {{ __('Save') }}</button>
						</div>
					</div>
				</div>
			</div>
			<div class="single-area">
				<div class="card sub">
					<div class="card-body">
						<h5>{{ __('Status') }}</h5>
						<hr>
						<select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="status">
							<option selected value="1" @if($info->status==1) selected="" @endif>{{ __('Published') }}</option>
							<option value="2" @if($info->status==2) selected="" @endif>{{ __('Draft') }}</option>

					</select>
				</div>
			</div>
		</div>
	<input type="hidden" name="type" value="1">
	<input type="hidden"  name="post_type" value="page">
</form>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>

<script>
"use strict";
//error response will assign this function
function errosresponse(xhr){
	$("#errors").html("<li class='text-danger'>"+xhr.responseJSON[0]+"</li>")
} 
</script>
@endsection

script/resources/views/admin/page/index.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card"  >
	<div class="card-body">
		<div class="row mb-30">
			<div class="col-lg-6">
				<h4>{{ __('Page List') }}</h4>
			</div>
			<div class="col-lg-6">
				<div class="add-new-btn">
					<a href="{{ route('admin.page.create') }}" class="btn btn-primary f-right">{{ __('Add New') }}</a>
				</div>
			</div>
		</div>
		<div class="cart-filter mb-20">
			<a href="{{ route('admin.page.index') }}">{{ __('All') }} <span>({{ App\Terms::where('type',1)->where('status','!=',0)->count() }})</span></a>
			<a href="?st=1">{{ __('Published') }} <span>({{ App\Terms::where('type',1)->where('status',1)->count() }})</span></a>
			<a href="?st=2">{{ __('Drafts') }} <span>({{ App\Terms::where('type',1)->where('status',2)->count() }})</span></a>
			<a href="?st=trash" class="trash">{{ __('Trash') }} <span>({{ App\Terms::where('type',1)->where('status',0)->count() }})</span></a>
		</div>
		<div class="card-action-filter">
			<form method="post" id="basicform" action="{{ route('admin.page.destroy') }}">
				@csrf
				<div class="row">
					<div class="col-lg-6">
						<div class="d-flex">
							<div class="single-filter">
								<div class="form-group">
									<select class="form-control" name="status">
										<option value="publish">{{ __('Publish') }}</option>
										<option value="trash">{{ __('Move to Trash') }}</option>
										<option value="delete">{{ __('Delete Permanently') }}</option>

									</select>
								</div>
							</div>
							<div class="single-filter">
								<button type="submit" class="btn btn-primary mt-1 ml-1">{{ __('Apply') }}</button>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="single-filter f-right">
							<div class="form-group">
								<input type="text" id="data_search" class="form-control" placeholder="Enter Value">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="table-responsive custom-table">
				<table class="table">
					<thead>
						<tr>
							<th class="am-select">
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input checkAll" id="customCheck12">
									<label class="custom-control-label checkAll" for="customCheck12"></label>
								</div>
							</th>
							<th class="am-title">{{ __('Title') }}</th>
							<th class="am-title">{{ __('Url') }}</th>
							<th class="am-title">{{ __('Status') }}</th>
							<th class="am-date">{{ __('Last Update') }}</th>
						</tr>
					</thead>
					<tbody>
						@foreach($pages as $page)
						<tr>
							<th>
								<div class="custom-control custom-checkbox">
									<input type="checkbox" name="ids[]" class="custom-control-input" id="customCheck{{ $page->id }}" value="{{ $page->id }}">
									<label class="custom-control-label" for="customCheck{{ $page->id }}"></label>
								</div>
							</th>
							<td>
								{{ $page->title }}
								<div class="hover">
									<a href="{{ route('admin.page.edit',$page->id) }}">{{ __('Edit') }}</a>

									<a href="{{ route('admin.page.edit',$page->id) }}" class="last">{{ __('View') }}</a>
								</div>
							</td>
								<td>{{ url('/page',$page->slug)  }}</td>
							<td>@if($page->status==1)  {{ __('Published') }} @elseif($page->status==2)  Draft @else {{ __('Trash') }} @endif</td>
							<td>{{ __('Last Modified') }}
								<div class="date">
									{{ $page->updated_at->diffForHumans() }}
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</form>
				<tfoot>
					<tr>
						<th class="am-select">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input checkAll" id="customCheck12">
								<label class="custom-control-label checkAll" for="customCheck12"></label>
							</div>
						</th>
						<th class="am-title">{{ __('Title') }}</th>
						<th class="am-title">{{ __('Url') }}</th>
						<th class="am-title">{{ __('Status') }}</th>
						<th class="am-date">{{ __('Last Update') }}</th>
					</tr>
				</tfoot>
			</table>
			{{ $pages->links() }}

		</div>
	</div>
</div>
@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script type="text/javascript">
	"use strict";	
	//response will assign this function
	function success(res){
		location.reload();
	}
	
</script>
@endsection