script/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// All installer route are here
Route::get('install','Installer\InstallerController@install')->name('install');
Route::get('install/purchase','Installer\InstallerController@purchase')->name('purchase');
Route::post('install/purchase_check','Installer\InstallerController@purchase_check')->name('purchase_check');
Route::get('install/check','Installer\InstallerController@check')->name('install.check');
Route::get('install/info','Installer\InstallerController@info')->name('install.info');
Route::get('install/migrate','Installer\InstallerController@migrate')->name('install.migrate');
Route::get('install/seed','Installer\InstallerController@seed')->name('install.seed');
Route::post('install/store','Installer\InstallerController@send');
Route::get('404',function(){
	return abort(404);
})->name(404);


// // sitemap route
Route::get('/sitemap.xml', 'SettingController@sitemapView');

Route::get('locale','LocalizationController@store')->name('language.set'); 
// laravel auth routes
Auth::routes(['verify' => true]);
Route::get('/mysettings','Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
Route::post('genup','Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
Route::post('passup','Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');



Route::get('test', function(Request $request) {
    dd($request);
});
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
|
*/

//Admin settings route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){
	//dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('announcement','DashboardController@announcement')->name('announcement');
	// page resource route
	Route::resource('page','PageController');
	Route::post('pages/destroy','PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post','PostController');
	Route::post('post/destroy','PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment','CommentController');
	Route::get('/comment/disqus','CommentController@apiview')->name('dsiqus.settings');

	Route::post('blog/comments/destroy','CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}','CommentController@reply')->name('comment.reply');
	Route::resource('blog/category','CategoryController');

	Route::post('disqus','CommentController@disqus')->name('disqus.store');

	// category route
	Route::post('categorys','CategoryController@destroy')->name('categorys.destroy');
	Route::resource('settings','SettingsController');
	// menu route
	Route::resource('appearance/menu','MenuController');
	Route::post('menues/destroy','MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node','MenuController@MenuNodeStore')->name('menus.MenuNodeStore');
	//theme route 
	Route::get('appearance/theme','ThemeController@index')->name('theme.index');
	Route::get('theme/{name}','ThemeController@active')->name('theme.active');
	Route::post('theme/upload','ThemeController@upload')->name('theme.upload');
	//widget route 
	Route::get('appearance/widget','WidgetController@index')->name('widget.index');
	//themeoptions route
	Route::get('appearance/themeoptions','ThemeoptionsController@index')->name('themeoptions.index');
	//script route
	Route::resource('appearance/script','ScriptController');
	//Plugin route
	Route::get('plugin','PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}','PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}','PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload','PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo','SeoController');

	//env route
	Route::resource('setting/env','EnvController');
	Route::resource('setting/filesystem','FilesystemController');

	//performance route
	Route::resource('setting/performance','PerfomaceController');


	//general route
	Route::resource('setting/general','GensettingsController');


	//permission route
	Route::get('permission','PermissionController@index')->name('permission.index');


	//usersystem route
	Route::get('usersystem','UsersystemController@index')->name('usersystem.index');


	//information route
	Route::get('information','InformationController@index')->name('information.index');

	//permissions
	Route::resource('permission','PermissionController');

	//langauge route
	Route::resource('language','LanguageController');


	//Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');

});


/*
|--------------------------------------------------------------------------
| Store Routes
|--------------------------------------------------------------------------
|
| All Store routes are here
|
|
*/
Route::group(['as' =>'store.','prefix'=>'store','namespace'=>'Store','middleware'=>['auth','store','verified','approval']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('status','DashboardController@status')->name('status');
});


Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::resource('media','MediaController');
	Route::get('medias/json','MediaController@json')->name('medias.json');
	Route::get('media/info/{id}','MediaController@show');
	Route::post('medias/remove','MediaController@destroy')->name('medias.destroy');
	
});

// Social Login Route
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

script/app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
	protected $table="comments";
	public function term()
	{
		return $this->belongsTo('App\Terms');
	}

	public function reply()
	{
		return $this->hasMany('App\Comment','p_id','id');
	}

	public function comment_meta()
	{
		return $this->belongsTo('App\Commentmeta','id','comment_id');
	}
}

script/app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Comment;
use App\Options;
use Auth;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
        if ($request->qry==1) {
             $comments=Comment::with('term')->where('status',1)->where('p_id',null)->latest()->paginate(20);
             $status=1;
             return view('admin.comment.index',compact('comments','status'));
        }
         if ($request->qry=='replyed') {
             $comments=Comment::with('term')->where('p_id',null)->where('status',4)->latest()->paginate(20);
             $status=4;
             return view('admin.comment.index',compact('comments','status'));
        }
         elseif ($request->qry=='adminreplyed') {
             $comments=Comment::with('term')->where('status',4)->latest()->paginate(20);
             $status=4;
             return view('admin.comment.index',compact('comments','status'));
        }

        elseif ($request->qry==2) {
             $comments=Comment::with('term')->where('status',2)->where('p_id',null)->latest()->paginate(20);
             $status=2;
            
             return view('admin.comment.index',compact('comments','status'));
        }
         elseif ($request->qry==3) {
             $comments=Comment::with('term')->where('status',3)->where('p_id',null)->latest()->paginate(20);
             $status=3;
             return view('admin.comment.index',compact('comments','status'));
        }
        elseif ($request->qry=='trash') {
             $comments=Comment::with('term')->where('status',0)->latest()->paginate(20);
             $status=0;
             return view('admin.comment.index',compact('comments','status'));
        }
        $status=1;
        $comments=Comment::with('term')->where('status','!=',0)->where('p_id',null)->latest()->paginate(20);
        return view('admin.comment.index',compact('comments','status'));
    }


    public function apiview()
    {
        return view('admin.comment.settings');
    }

    public function disqus(Request $request)
    {
        $option=Options::where('key','disqus_comment')->first();
        if (empty($option)) {
            $option= new Options;
           
        }
        $option->key="disqus_comment";
        $option->value=$request->disqus;
        $option->save();
        return response()->json(['Disqus comment configured successfully']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comments= Comment::find($request->id);
        $comments->status = 4;
        $comments->save();

        $comment=new Comment;
        $comment->term_id=$request->post_id;
        $comment->p_id=$request->id;
        $comment->auth_id=Auth::id();
        $comment->comment=$request->reply;
        $comment->status=4;
        $comment->save();
        return response()->json(['Reply Success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $comments=Comment::with('reply')->find($id);
        
        
        return view('admin.comment.reply',compact('comments'));
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }


   

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        
   
        if ($request->status != 'delete') {

            if ($request->ids) {
                foreach ($request->ids as $id) {
                    $comment=Comment::find($id);
                    $comment->status=$request->status;
                    $comment->Save();
                   
                }
            }
            return response()->json('Success');
        }

         if ($request->status=='delete') {
             if ($request->ids) {
                foreach ($request->ids as $id) {
                   Comment::where('p_id',$id)->delete();
                   Comment::destroy($id);
                   
                }
                return response()->json('Success');
            }
         }
            
       
    }
}

script/resources/views/admin/comment/index.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card"  >
	<div class="card-body">
		<div class="row mb-30">
			<div class="col-lg-6">
				<h4>{{ __('Comment List') }}</h4>
			</div>
			<div class="col-lg-6 text-right">
				<a href="{{ route('admin.dsiqus.settings') }}" class="btn btn-primary"  >{{ __('Disqus Comment Settings') }}</a>
			</div>
		</div>
		<div class="cart-filter mb-20">
			<a href="{{ route('admin.comment.index') }}">All <span>({{ App\Comment::where('p_id',null)->count() }})</span></a>
			<a href="?qry=1">{{ __('Approved') }} <span>({{ App\Comment::where('status',1)->where('p_id',null)->count() }})</span></a>
			<a href="?qry=replyed">{{ __('Replyed') }} <span>({{ App\Comment::where('p_id',null)->where('status',4)->count() }})</span></a>
			<a href="?qry=adminreplyed">{{ __('Admin Replyed') }} <span>({{ App\Comment::where('p_id','!=',null)->where('status',4)->count() }})</span></a>
			
			<a href="?qry=2">{{ __('Pending') }} <span>({{ App\Comment::where('status',2)->where('p_id',null)->count() }})</span></a>
			<a href="?qry=3">{{ __('Unapproved') }} <span>({{ App\Comment::where('status',3)->where('p_id',null)->count() }})</span></a>
			<a href="?qry=trash" class="trash">{{ __('Trash') }} <span>({{ App\Comment::where('status',0)->where('p_id',null)->count() }})</span></a>
		</div>
		<div class="card-action-filter">
			<form method="post" id="basicform" action="{{ route('admin.comments.destroy') }}">
				@csrf
				<div class="row">
					<div class="col-lg-6">
						<div class="d-flex">
							<div class="single-filter">
								<div class="form-group">
									<select class="form-control" name="status">
										<option>{{ __('Select Action') }}</option>
										<option value="1">{{ __('Approved') }}</option>
										<option value="3">{{ __('Unapproved') }}</option>
										@if($status != 0)
										<option value="0">{{ __('Move to Trash') }}</option>
										@endif
										@if($status==0)
										<option value="delete">{{ __('Delete Permanently') }}</option>
										@endif
									</select>
								</div>
							</div>
							<div class="single-filter">
								<button type="submit" class="btn">{{ __('Apply') }}</button>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="single-filter f-right">
							<div class="form-group">
								<input type="text" id="data_search" class="form-control" placeholder="Enter Value">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="table-responsive custom-table">
				<table class="table">
					<thead>
						<tr>
							<th class="am-select">
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input checkAll" id="customCheck12">
									<label class="custom-control-label checkAll" for="customCheck12"></label>
								</div>
							</th>
							<th class="am-title">{{ __('Author') }}</th>
							<th class="am-title">{{ __('Comment') }}</th>
							<th class="am-title">{{ __('Status') }}</th>
							<th class="am-title">{{ __('Submitted On') }}</th>
						</tr>
					</thead>
					<tbody>
						@foreach($comments as $comment)
						<tr>
							<th>
								<div class="custom-control custom-checkbox">
									<input type="checkbox" name="ids[]" class="custom-control-input" id="customCheck{{ $comment->id }}" value="{{ $comment->id }}">
									<label class="custom-control-label" for="customCheck{{ $comment->id }}"></label>
								</div>
							</th>
							<td>@if($comment->auth_id != null) {{ App\User::where('id',$comment->auth_id)->first()->name }} @endif</td>
							<td>
								{{ $comment->comment }}
								<div class="hover">
									@if($comment->status != 4)
									<a href="{{ route('admin.comment.show',$comment->id) }}">{{ __('Reply') }}</a>
									@endif
									
									<a href="{{ url('/post/'.$comment->term->slug) }}" target="_blank" class="last">{{ __('View') }}</a>
								</div>
							</td>
							<td>@if($comment->status==1)
								{{ __('Approved') }}
								@elseif($comment->status==2)
								{{ __('Pending') }}
								@elseif($comment->status==3)
								{{ __('Unapproved') }}
								@elseif($comment->status == 4)
								{{ __('Replyed') }}
								@else {{ __('Trash') }}
							@endif</td>
							<td>{{ __('Last Modified') }}
								<div class="date">
									{{ $comment->created_at->diffForHumans() }}
								</div>
							</td>
						</tr>

						@endforeach
					</tbody>
				</form>
				<tfoot>
					<tr>
						<th class="am-select">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input checkAll" id="customCheck12">
								<label class="custom-control-label checkAll" for="customCheck12"></label>
							</div>
						</th>
						<th class="am-title">{{ __('Author') }}</th>
						<th class="am-title">{{ __('Comment') }}</th>
						<th class="am-title">{{ __('Status') }}</th>
						<th class="am-title">{{ __('Submitted On') }}</th>
					</tr>
				</tfoot>
			</table>
			{{ $comments->links() }}
		</div>
	</div>
</div>


@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script type="text/javascript">
	"use strict";
	//response function
	function success(res){
		location.reload();
	}
</script>
@endsection

script/resources/views/admin/comment/reply.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card"  >
	<div class="card-body">
		<div class="row mb-30">
			<div class="col-lg-12">
				<h4>{{ __('Reply Comment') }}</h4>

				<p>{{ __('Name:') }} {{ $comments->name }}</p>
				<p>{{ __('Email:') }} {{ $comments->email }}</p>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="comment-reply-box">
					<div class="comment-chat">
						<section class="discussion">
							<div class="bubble sender">{{ $comments->comment }} </div>
							@foreach($comments->reply as $row)
								<div class="bubble recipient">{{ $row->comment }}</div>
							@endforeach
						</section>		
					</div>
				</div>
				<div class="write-comment">
					<form method="post" id="basicform" action="{{ route('admin.comment.store') }}">
					@csrf
					<input type="hidden" name="id" value="{{ $comments->id }}">
					<input type="hidden" name="post_id" value="{{ $comments->term_id }}">
					<input type="text" name="reply" id="reply_input" placeholder="Reply Comment">
					<button type="submit"><i class="far fa-paper-plane"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script type="text/javascript">
	"use strict";	
	//success response will assign this function
	function success(res){
		location.reload();
	}
</script>
@endsection

script/resources/views/admin/comment/settings.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card"  >
	<div class="card-body">
		<div class="row mb-30">
			<div class="col-lg-12">
				<h4>{{ __('Third Party API Settings') }}</h4>
			</div>
		</div>
		
		<div class="card-action-filter">
			<form method="post" action="{{ route('admin.disqus.store') }}" id="basicform">
				@csrf
				<div class="form-group">
					<label><a href="https://disqus.com/admin/create/" target="_blank">{{ __('Disqus') }}</a> {{ __('Comment API Source') }} </label><br>
					<small>{{ __('Your unique') }} <a href="https://disqus.com/admin/create/" target="_blank">{{ __('disqus') }}</a> {{ __('URL will be: shortname.disqus.com') }}</small>
					<input type="text" name="disqus" class="form-control" placeholder="Enter your unique url" required="" value="{{ \App\Options::where('key','disqus_comment')->first()->value }}">
				</div>
				<div class="form-group">
					<button class="btn" type="submit">{{ __('Submit') }}</button>
				</div>
			</form>
		</div>
	</div>
</div>

@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
@endsection