script/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// All installer route are here
Route::get('install','Installer\InstallerController@install')->name('install');
Route::get('install/purchase','Installer\InstallerController@purchase')->name('purchase');
Route::post('install/purchase_check','Installer\InstallerController@purchase_check')->name('purchase_check');
Route::get('install/check','Installer\InstallerController@check')->name('install.check');
Route::get('install/info','Installer\InstallerController@info')->name('install.info');
Route::get('install/migrate','Installer\InstallerController@migrate')->name('install.migrate');
Route::get('install/seed','Installer\InstallerController@seed')->name('install.seed');
Route::post('install/store','Installer\InstallerController@send');
Route::get('404',function(){
	return abort(404);
})->name(404);


// // sitemap route
Route::get('/sitemap.xml', 'SettingController@sitemapView');

Route::get('locale','LocalizationController@store')->name('language.set'); 
// laravel auth routes
Auth::routes(['verify' => true]);
Route::get('/mysettings','Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
Route::post('genup','Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
Route::post('passup','Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');



Route::get('test', function(Request $request) {
    dd($request);
});
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
|
*/

//Admin settings route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){
	//dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('announcement','DashboardController@announcement')->name('announcement');
	// page resource route
	Route::resource('page','PageController');
	Route::post('pages/destroy','PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post','PostController');
	Route::post('post/destroy','PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment','CommentController');
	Route::get('/comment/disqus','CommentController@apiview')->name('dsiqus.settings');

	Route::post('blog/comments/destroy','CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}','CommentController@reply')->name('comment.reply');
	Route::resource('blog/category','CategoryController');

	Route::post('disqus','CommentController@disqus')->name('disqus.store');

	// category route
	Route::post('categorys','CategoryController@destroy')->name('categorys.destroy');
	Route::resource('settings','SettingsController');
	// menu route
	Route::resource('appearance/menu','MenuController');
	Route::post('menues/destroy','MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node','MenuController@MenuNodeStore')->name('menus.MenuNodeStore');
	//theme route 
	Route::get('appearance/theme','ThemeController@index')->name('theme.index');
	Route::get('theme/{name}','ThemeController@active')->name('theme.active');
	Route::post('theme/upload','ThemeController@upload')->name('theme.upload');
	//widget route 
	Route::get('appearance/widget','WidgetController@index')->name('widget.index');
	//themeoptions route
	Route::get('appearance/themeoptions','ThemeoptionsController@index')->name('themeoptions.index');
	//script route
	Route::resource('appearance/script','ScriptController');
	//Plugin route
	Route::get('plugin','PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}','PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}','PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload','PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo','SeoController');

	//env route
	Route::resource('setting/env','EnvController');
	Route::resource('setting/filesystem','FilesystemController');

	//performance route
	Route::resource('setting/performance','PerfomaceController');


	//general route
	Route::resource('setting/general','GensettingsController');


	//permission route
	Route::get('permission','PermissionController@index')->name('permission.index');


	//usersystem route
	Route::get('usersystem','UsersystemController@index')->name('usersystem.index');


	//information route
	Route::get('information','InformationController@index')->name('information.index');

	//permissions
	Route::resource('permission','PermissionController');

	//langauge route
	Route::resource('language','LanguageController');


	//Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');

});


/*
|--------------------------------------------------------------------------
| Store Routes
|--------------------------------------------------------------------------
|
| All Store routes are here
|
|
*/
Route::group(['as' =>'store.','prefix'=>'store','namespace'=>'Store','middleware'=>['auth','store','verified','approval']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('status','DashboardController@status')->name('status');
});


Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::resource('media','MediaController');
	Route::get('medias/json','MediaController@json')->name('medias.json');
	Route::get('media/info/{id}','MediaController@show');
	Route::post('medias/remove','MediaController@destroy')->name('medias.destroy');
	
});

// Social Login Route
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

script/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $table="posts";

	public function term()
	{
		return $this->hasMany('App\Terms');
	}

}

script/app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Terms;
use App\Meta;
use App\Post;
use App\PostCategory;
use App\Postrelation;
use Auth;
use DB;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       
       
        
        if($request->src) {
           $posts=Terms::with('user')->where('type',0)->where('title','LIKE','%'.$request->src.'%')->latest()->paginate(20);
        }
        elseif($request->st) {
            if ($request->st=='trash') {
                 $posts=Terms::with('user')->where('type',0)->where('status',0)->latest()->paginate(20);
                 $status=$request->st;
                 return view('admin.posts.index',compact('posts','status'));
            }
            else{
               $posts=Terms::with('user')->where('type',0)->where('status',$request->st)->latest()->paginate(20);
               $status=$request->st;
               return view('admin.posts.index',compact('posts','status')); 
           }
           
       }
        else{
          $posts=Terms::with('user')->where('type',0)->latest()->where('status','!=',0)->paginate(20);
        }
        $status=1;
        return view('admin.posts.index',compact('posts','status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $validatedData = $request->validate([
            'title' => 'required|max:100',
            
        ]);


        $creat_slug=Str::slug($request->title);
        if ($creat_slug=='') {
            $creat_slug=str_replace(' ', '-', $request->title);
        }
        $check=Terms::where('slug',$creat_slug)->where('type',2)->count();
        if ($check != 0) {
            $slug=$creat_slug.'-'.$check;
        }
        else{
            $slug=$creat_slug;
        }


        


        $post=new Terms;
        $post->title=$request->title;
        $post->slug=$slug;
        $post->type=0;
        $post->auth_id=Auth::id();
        $post->lang=$request->lang;
        $post->status=$request->status;
        $post->lang=$request->lang;
        $post->save();

        $post_meta = new Meta;
        $post_meta->term_id=$post->id;
        $post_meta->type='excerpt';
        $post_meta->content=$request->excerpt;
        $post_meta->save();

        $post_meta = new Meta;
        $post_meta->term_id=$post->id;
        $post_meta->type='preview';
        $post_meta->content=$request->preview;
        $post_meta->save();

        $post_meta = new Meta;
        $post_meta->term_id=$post->id;
        $post_meta->type='content';
        $post_meta->content=$request->content;
        $post_meta->save();



        if ($request->category) {
            
         foreach ($request->category as $cat_row) {
           
                $cat= new PostCategory;
                $cat->term_id=$post->id;
                $cat->category_id=$cat_row;
                $cat->save();
          

         }
        }

        

        
        return response()->json('Post Created');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $info=Terms::with('excerpt','content','preview','categories')->find($id);   
       return view('admin.posts.edit',compact('info'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
      
         $validatedData = $request->validate([
            'title' => 'required|max:100',
            'slug' => 'required|max:100',
            
        ]);
         $slug= Terms::where('slug',$request->slug)->where('id','!=',$id)->first();
        if (!empty($slug)) {
            return response()->json(['Slug Must Be unique'],401);
        }

      

        $post= Terms::find($id);
        $post->title=$request->title;
        $post->slug=$request->slug;
        $post->auth_id=Auth::id();
        $post->lang=$request->lang;
        $post->status=$request->status;
        $post->lang=$request->lang;
        $post->save();

        $post_meta =  Meta::where('term_id',$id)->where('type','excerpt')->first();
        if (!empty($post_meta)) {
          $post_meta->content=$request->excerpt;
          $post_meta->save();
      }
       
        $postdetail =  Meta::where('term_id',$id)->where('type','content')->first();
       
        if (!empty($postdetail)) {
            $post_meta->content=$request->content;
            $postdetail->save();
        }

        $pr =  Meta::where('term_id',$id)->where('type','preview')->first();
       
        if (!empty($pr)) {
            $pr->content=$request->preview;
            $pr->save();
        }
        


        if ($request->category) {
          PostCategory::where('term_id',$id)->delete();    
         foreach ($request->category as $cat_row) {
            if ($cat_row != 0) {
                $cat= new PostCategory;
                $cat->term_id=$id;
                $cat->category_id=$cat_row;
                $cat->save();
            }

         }
        }

      
       

        return response()->json('Post updated');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        if ($request->status=='publish') {
            if ($request->ids) {

                foreach ($request->ids as $id) {
                    $post=Terms::find($id);
                    $post->status=1;
                    $post->save();   
                }
                    
            }
        }
        elseif ($request->status=='trash') {
            if ($request->ids) {
                foreach ($request->ids as $id) {
                    $post=Terms::find($id);
                    $post->status=0;
                    $post->save();   
                }
                    
            }
        }
        elseif ($request->status=='delete') {
            if ($request->ids) {
                foreach ($request->ids as $id) {
                   Terms::destroy($id);
                   
                }
            }
        }
        return response()->json('Success');

    }
}

script/resources/views/admin/posts/create.blade.php
@extends('layouts.backend.app')

@section('style')
<link rel="stylesheet" href="{{ asset('admin/css/summernote.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin/css/bootstrap-tagsinput.css') }}">
@endsection

@section('content')
<div class="row">
 <div class="col-lg-9">      
  <div class="card">
   <div class="card-body">
     <div class="alert alert-danger none errorarea">
      <ul id="errors">

      </ul>
    </div>
    <h4>{{ __('Add new Post') }}</h4>
    <form method="post" id="basicform" action="{{ route('admin.post.store') }}">
     @csrf
     <div class="custom-form pt-20">
      
     @php
     $arr['title']= 'Post Title';
     $arr['id']= 'name';
     $arr['type']= 'text';
     $arr['placeholder']= 'Post Title';
     $arr['name']= 'title';
     $arr['is_required'] = true;

     echo  input($arr);

     $arr['title']= 'Excerpt';
     $arr['id']= 'excerpt';
     $arr['placeholder']= 'short description';
     $arr['name']= 'excerpt';
     $arr['is_required'] = true;

     echo  textarea($arr);
     
     $arrn['title']= 'Post Content';
     $arrn['name']= 'content';
    
     echo  editor($arrn);
     @endphp
     
   </div>
 </div>
</div>

</div>
<div class="col-lg-3">
  <div class="single-area">
   <div class="card">
    <div class="card-body">
     <h5>{{ __('Publish') }}</h5>
     <hr>
     <div class="btn-publish">
      <button type="submit" class="btn btn-primary col-12"><i class="fa fa-save"></i> {{ __('Save') }}</button>
    </div>
  </div>
</div>
</div>
<div class="single-area">
 <div class="card sub">
  <div class="card-body">
   <h5>{{ __('Status') }}</h5>
   <hr>
   <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="status">
    <option value="1">{{ __('Published') }}</option>
    <option value="2">{{ __('Draft') }}</option>

  </select>
</div>
</div>
</div>
<?php echo adminLang(); ?>
<div class="single-area">
 <div class="card sub">
  <div class="card-body">
   <h5>{{ __('Categories') }}</h5>
   <hr>
   <div class="scroll-bar-wrap">
     <div class="category-list">
       {{ AdminCategory(0) }}
       <div class="cover-bar"></div>
     </div>
   </div>
 </div>
</div>
</div>


{{ mediasection() }}


<div class="single-area">
  <div class="card sub">
    <div class="card-body">
      <h5>{{ __('Tags') }}</h5>
      <hr>
      <input type="text" name="tag" id="tags" class="form-control">
    </div>
  </div>
</div>
<div class="single-area">
  <div class="card sub">
    <div class="card-body">
      <h5>{{ __('Comment Status') }}</h5>
      <hr>
      <select class="form-control" name="comment_status">
        <option value="1">{{ __('Allowed Comment') }}</option>
        <option value="0">{{ __('Comment Not Allow') }}</option>
        
      </select>
    </div>
  </div>
</div>
</div>
</div>
<input type="hidden"  name="type" value="0">
<input type="hidden"  name="post_type" value="blog">
<button type="button" data-toggle="modal" data-target=".media-multiple" class="multi-modal" class="btn bg-btn" >test</button>


</form>

{{ mediasingle() }}
@include('admin.media.multiplemediamodel')
@endsection

@section('script')
<script src="{{ asset('admin/js/summernote.min.js') }}"></script>
<script src="{{ asset('admin/js/custom-summernote.min.js') }}"></script>
<script src="{{ asset('admin/js/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('admin/js/form.js') }}"></script>
<script src="{{ asset('admin/js/media.js') }}"></script>
<script>
  (function ($) {
    "use strict";

    $('#tags').tagsinput();
    $('.use').on('click',function(){

      $('#preview').attr('src',myradiovalue);
      $('#preview_input').val(myradiovalue);
      
    });

    //for multiple
    $('.use1').on('click',function(){
      $('.multi-img').hide();
      $('.gallary-src').remove();
      $.each(mycheckboxvalue, function(index, value){
        $(".gallary-img").append('<img class="gallary-src" src="' + value + '" />');
      });

      $('#gallary_input').val(mycheckboxvalue.toString())

    });
})(jQuery);
//response will assign this function
function success(res){
  location.reload();
}
</script>
@endsection

script/resources/views/admin/posts/edit.blade.php
@extends('layouts.backend.app')

@section('style')
<link rel="stylesheet" href="{{ asset('admin/css/bootstrap-tagsinput.css') }}">
@endsection

@section('content')
<div class="row">
 <div class="col-lg-9">      
  <div class="card">
   <div class="card-body">
     <div class="alert alert-danger none errorarea">
      <ul id="errors">

      </ul>
    </div>
    <h4>{{ __('Edit Post') }}</h4>
    <form method="post" id="basicform" action="{{ route('admin.post.update',$info->id) }}">
     @csrf
     @method('PUT')

     <div class="custom-form pt-20">
       @php
     $arr['title']= 'Post Title';
     $arr['id']= 'name';
     $arr['type']= 'text';
     $arr['placeholder']= 'Post Title';
     $arr['name']= 'title';
     $arr['is_required'] = true;
     $arr['value'] = $info->title;

     echo  input($arr);

     $arr1['title']= 'Post Slug';
     $arr1['id']= 'slug';
     $arr1['type']= 'text';
     $arr1['placeholder']= 'Post Slug';
     $arr1['name']= 'slug';
     $arr1['is_required'] = true;
     $arr1['value'] = $info->slug;

     echo  input($arr1);

     $arr['title']= 'Excerpt';
     $arr['id']= 'excerpt';
     $arr['placeholder']= 'short description';
     $arr['name']= 'excerpt';
     $arr['is_required'] = true;
     $arr['value'] = $info->excerpt->content;

     echo  textarea($arr);
     
     $arrn['title']= 'Post Content';
     $arrn['name']= 'content';
     $arrn['value']= $info->content->content;
    
     echo  editor($arrn);
     @endphp
      
 </div>
</div>
</div>
<div class="card">
  <div class="card-body">
   <h4>{{ __('Search Engine Optimization') }}</h4>
   <div class="search-engine">
    <h6 class="pt-15 page-title-seo" id="seotitle">{{ $info->title }}</h6>
    <a href="#" class="text-success" id="seourl">'{{ url('/').'/post/'.$info->slug }}</a>
    <p id="seodescription">{{ $info->excerpt->content }}</p>
  </div>

</div>
</div>
</div>
<div class="col-lg-3">
  <div class="single-area">
   <div class="card">
    <div class="card-body">
     <h5>{{ __('Publish') }}</h5>
     <hr>
     <div class="btn-publish">
      <button type="submit" class="btn btn-save"><i class="fa fa-save"></i> {{ __('Save') }}</button>
    </div>
  </div>
</div>
</div>
<div class="single-area">
 <div class="card sub">
  <div class="card-body">
   <h5>{{ __('Status') }}</h5>
   <hr>
   <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" name="status">
    <option value="1" @if($info->status == 1) selected="" @endif>{{ __('Published') }}</option>
    <option value="2" @if($info->status == 2) selected="" @endif>{{ __('Draft') }}</option>

  </select>
</div>
</div>
</div>
<?php echo adminLang($info->lang); ?>
<div class="single-area">
 <div class="card sub">
  <div class="card-body">
   <h5>{{ __('Categories') }}</h5>
   <hr>
   <div class="scroll-bar-wrap">
     <div class="category-list">

      @php
      $catArr=[];

      foreach ($info->categories as $row) {
        array_push($catArr, $row->id);
      }
      
      @endphp  

      <?php echo AdminCategoryUpdate(0, $catArr); ?>

      <div class="cover-bar"></div>
    </div>
  </div>
</div>
</div>
</div>
<?php 
if(!empty($info->preview)){
  
    $media['preview'] = $info->preview->content;
    $media['value'] = $info->preview->content;
    echo  mediasection($media);
}
else{
 echo mediasection();
}

?>
<div class="single-area">
  <div class="card sub">
    <div class="card-body">
      <h5>{{ __('Tags') }}</h5>
      <hr>
      <input type="text" name="tag" id="tags" class="form-control" value="{{ $info->tags ?? '' }}">
    </div>
  </div>
</div>
<div class="single-area">
  <div class="card sub">
    <div class="card-body">
      <h5>{{ __('Comment Status') }}</h5>
      <hr>
    </div>
  </div>
</div>
</div>
</div>
</form>
{{ mediasingle() }}

@endsection

@section('script')
<script src="{{ asset('admin/js/summernote.min.js') }}"></script>
<script src="{{ asset('admin/js/custom-summernote.min.js') }}"></script>
<script src="{{ asset('admin/js/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('admin/js/form.js') }}"></script>
<script src="{{ asset('admin/js/media.js') }}"></script>
<script>
  (function ($) {
    "use strict";
    $('#tags').tagsinput();
    $('.use').on('click',function(){

      $('#preview').attr('src',myradiovalue);
      $('#preview_input').val(myradiovalue);

    });

    $('.use1').on('click',function(){
      $('.multi-img').remove();

      $('.gallary-src').remove();

      $.each(mycheckboxvalue, function(index, value){
        $(".gallary-img").append('<img class="gallary-src" src="' + value + '" />');
      });

      $('#gallary_input').val(mycheckboxvalue.toString())

    });


    $('#slug').on('input',function(){

      $('#seotitle').html($('#slug').val());
      let slug = $('#slug').val().replace(" ", "-");
      $('#seourl').html('{{ url('/').'/post/' }}'+slug)
    })
    $('#description').on('input',function(){
      $('#seodescription').html($('#description').val());
    })

  })(jQuery); 


//response will assign this function
function success(res){
  Sweet('success','Post Updated')
}
function errosresponse(xhr){
  $("#errors").html("<li class='text-danger'>"+xhr.responseJSON[0]+"</li>")
}
</script>
@endsection

script/resources/views/admin/posts/index.blade.php
@section('style')

@endsection
@extends('layouts.backend.app')

@section('content')

<div class="card">
	<div class="card-body">
		<div class="row mb-30">
			<div class="col-lg-6">
				<h4>{{ __('Posts List') }}</h4>
			</div>
			<div class="col-lg-6">
				<div class="add-new-btn">
					<a href="{{ route('admin.post.create') }}" class="btn btn-primary f-right">{{ __('Add New') }}</a>
				</div>
			</div>
		</div>
		<div class="cart-filter mb-20">
			<a href="{{ route('admin.post.index') }}">{{ __('All') }} <span>({{ App\Terms::where('type',0)->where('status','!=',0)->count() }})</span></a>
			<a href="?st=1">{{ __('Published') }} <span>({{ App\Terms::where('type',0)->where('status',1)->count() }})</span></a>
			<a href="?st=2">{{ __('Drafts') }} <span>({{ App\Terms::where('type',0)->where('status',2)->count() }})</span></a>
			<a href="?st=trash" class="trash">{{ __('Trash') }} <span>({{ App\Terms::where('type',0)->where('status',0)->count() }})</span></a>
		</div>
		<div class="card-action-filter">
			<div class="row mb-10">
				<div class="col-lg-6">
					<form id="basicform" method="post" action="{{ route('admin.post.destroys') }}">
						@csrf
						<div class="d-flex">
							<div class="single-filter">
								<div class="form-group">
									<select class="form-control" name="status">
										<option>{{ __('Bulk Actions') }}</option>
										<option value="publish">{{ __('Publish') }}</option>
										<option value="trash">{{ __('Move to Trash') }}</option>
										<option value="delete">{{ __('Delete Permanently') }}</option>
									</select>
								</div>
							</div>
							<div class="single-filter">
								<button type="submit" class="btn">{{ __('Apply') }}</button>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="single-filter f-right">
							<div class="form-group">
								
								<input type="text" id="data_search" class="form-control" placeholder="Enter Value">
								
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="table-responsive custom-table">
				<table class="table">
					<thead>
						<tr>
							<th class="am-select">
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input checkAll" id="checkAll">
									<label class="custom-control-label" for="checkAll"></label>
								</div>
							</th>
							<th class="am-title">{{ __('Title') }}</th>
							<th class="am-author">{{ __('Author') }}</th>
							
							<th class="am-tags">{{ __('Views') }}</th>
							<th class="am-tags">{{ __('Lang') }}</th>
							<th class="am-tags">{{ __('Status') }}</th>

							<th class="am-date">{{ __('Last Modified') }}</th>
						</tr>
					</thead>
					<tbody>
						@foreach($posts as $post)
						<tr>
							<th>
								<div class="custom-control custom-checkbox">
									<input type="checkbox" name="ids[]" class="custom-control-input" id="customCheck{{ $post->id }}" value="{{ $post->id }}">
									<label class="custom-control-label" for="customCheck{{ $post->id }}"></label>
								</div>
							</th>
							<td>
								{{ $post->title }}
								<div class="hover">
									<a href="{{ route('admin.post.edit',$post->id) }}">{{ __('Edit') }}</a>

									<a href="{{ route('admin.post.edit',$post->id) }}" class="last">{{ __('View') }}</a>
								</div>
							</td>
							<td>{{ $post->user->name }}</td>
							
							<td>{{ $post->count }}</td>
							<td>{{ $post->lang }}</td>
							<td>@if($post->status==1)  Published @elseif($post->status==2)  {{ __('Draft') }} @else {{ __('Trash') }} @endif</td>
							<td>{{ __('Last Modified') }}
								<div class="date">
									{{ $post->updated_at->diffForHumans() }}
								</div>
							</td>
						</tr>
						@endforeach

					</tbody>

					<tfoot>
						<tr>
							<th class="am-select">
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input checkAll" id="checkAll">
									<label class="custom-control-label" for="checkAll"></label>
								</div>
							</th>
							<th class="am-title">{{ __('Title') }}</th>
							<th class="am-author">{{ __('Author') }}</th>
							<th class="am-tags">{{ __('Views') }}</th>
							<th class="am-tags">{{ __('Lang') }}</th>
							<th class="am-tags">{{ __('Status') }}</th>

							<th class="am-date">{{ __('Last Modified') }}</th>
						</tr>
					</tfoot>
				</table>
			{{ $posts->links() }}
		</div>
	</div>
</div>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script>
"use strict";	
	//success response will assign this function
 function success(res){
 	location.reload();
 }
 function errosresponse(xhr){

 	$("#errors").html("<li class='text-danger'>"+xhr.responseJSON[0]+"</li>")
 }
</script>
@endsection