script/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// All installer route are here
Route::get('install','Installer\InstallerController@install')->name('install');
Route::get('install/purchase','Installer\InstallerController@purchase')->name('purchase');
Route::post('install/purchase_check','Installer\InstallerController@purchase_check')->name('purchase_check');
Route::get('install/check','Installer\InstallerController@check')->name('install.check');
Route::get('install/info','Installer\InstallerController@info')->name('install.info');
Route::get('install/migrate','Installer\InstallerController@migrate')->name('install.migrate');
Route::get('install/seed','Installer\InstallerController@seed')->name('install.seed');
Route::post('install/store','Installer\InstallerController@send');
Route::get('404',function(){
	return abort(404);
})->name(404);


// // sitemap route
Route::get('/sitemap.xml', 'SettingController@sitemapView');

Route::get('locale','LocalizationController@store')->name('language.set'); 
// laravel auth routes
Auth::routes(['verify' => true]);
Route::get('/mysettings','Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
Route::post('genup','Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
Route::post('passup','Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');



Route::get('test', function(Request $request) {
    dd($request);
});
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
|
*/

//Admin settings route
Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']],function(){
	//dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('announcement','DashboardController@announcement')->name('announcement');
	// page resource route
	Route::resource('page','PageController');
	Route::post('pages/destroy','PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post','PostController');
	Route::post('post/destroy','PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment','CommentController');
	Route::get('/comment/disqus','CommentController@apiview')->name('dsiqus.settings');

	Route::post('blog/comments/destroy','CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}','CommentController@reply')->name('comment.reply');
	Route::resource('blog/category','CategoryController');

	Route::post('disqus','CommentController@disqus')->name('disqus.store');

	// category route
	Route::post('categorys','CategoryController@destroy')->name('categorys.destroy');
	Route::resource('settings','SettingsController');
	// menu route
	Route::resource('appearance/menu','MenuController');
	Route::post('menues/destroy','MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node','MenuController@MenuNodeStore')->name('menus.MenuNodeStore');
	//theme route 
	Route::get('appearance/theme','ThemeController@index')->name('theme.index');
	Route::get('theme/{name}','ThemeController@active')->name('theme.active');
	Route::post('theme/upload','ThemeController@upload')->name('theme.upload');
	//widget route 
	Route::get('appearance/widget','WidgetController@index')->name('widget.index');
	//themeoptions route
	Route::get('appearance/themeoptions','ThemeoptionsController@index')->name('themeoptions.index');
	//script route
	Route::resource('appearance/script','ScriptController');
	//Plugin route
	Route::get('plugin','PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}','PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}','PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload','PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo','SeoController');

	//env route
	Route::resource('setting/env','EnvController');
	Route::resource('setting/filesystem','FilesystemController');

	//performance route
	Route::resource('setting/performance','PerfomaceController');


	//general route
	Route::resource('setting/general','GensettingsController');


	//permission route
	Route::get('permission','PermissionController@index')->name('permission.index');


	//usersystem route
	Route::get('usersystem','UsersystemController@index')->name('usersystem.index');


	//information route
	Route::get('information','InformationController@index')->name('information.index');

	//permissions
	Route::resource('permission','PermissionController');

	//langauge route
	Route::resource('language','LanguageController');


	//Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');

});


/*
|--------------------------------------------------------------------------
| Store Routes
|--------------------------------------------------------------------------
|
| All Store routes are here
|
|
*/
Route::group(['as' =>'store.','prefix'=>'store','namespace'=>'Store','middleware'=>['auth','store','verified','approval']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::post('status','DashboardController@status')->name('status');
});


Route::group(['as' =>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
	// dashboard route
	Route::get('dashboard','DashboardController@dashboard')->name('dashboard');
	Route::resource('media','MediaController');
	Route::get('medias/json','MediaController@json')->name('medias.json');
	Route::get('media/info/{id}','MediaController@show');
	Route::post('medias/remove','MediaController@destroy')->name('medias.destroy');
	
});

// Social Login Route
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

script/app/Customizer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customizer extends Model
{
    //
}

script/app/Http/Controllers/Admin/CustomizerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Customizer;
use Illuminate\Support\Arr;
use App\Media;
use File;
use Auth;

class CustomizerController extends Controller
{
	public function index()
	{
		$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
		$themes = json_decode($file, true);
		foreach ($themes as $theme) {
			if ($theme['status'] == 'active') {
				$customizer_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json');
				$active_theme = json_decode($customizer_file,true);
				foreach ($active_theme as $key => $value) {
					if ($value['status'] == 'active') {
						$main_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/views/'.$value['file_location']);
						$sidebar_options = json_decode($main_file,true);

					}
				}
			}
		}
		return view('admin.customizer.index',compact('active_theme','sidebar_options'));
	}

	public function page_change(Request $request)
	{
		$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
		$themes = json_decode($file, true);
		foreach ($themes as $theme) {
			if ($theme['status'] == 'active') {
				$customizer_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json');
				$active_theme = json_decode($customizer_file,true);

				foreach ($active_theme as $key=> $value) {
					if ($value['status'] == 'active') {
						$active_theme[$key]['status'] = "deactive";
					}
					if ($value['page_name'] == $request->page_name) {
						$active_theme[$key]['status'] = "active";
					}
				}
				file_put_contents(base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json', json_encode($active_theme,JSON_PRETTY_PRINT));
				return "ok";
			}
		}
		
	}

	public function section_option(Request $request)
	{
		$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
		$themes = json_decode($file, true);
		foreach ($themes as $theme) {
			if ($theme['status'] == 'active') {
				$customizer_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json');
				$active_theme = json_decode($customizer_file,true);
				foreach ($active_theme as $key => $value) {
					if ($value['status'] == 'active') {
						$main_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/views/'.$value['file_location']);
						$sidebar_options = json_decode($main_file,true);

						foreach ($sidebar_options as $key => $option) {
							if ($option['id'] == $request->id) {
								return view('admin.customizer.details',compact('option'));
							}
						}

					}
				}
			}
		}
	}


	public function value_update(Request $request)
	{


		if ($request->option == 'key') {
			$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
			$themes = json_decode($file, true);
			foreach ($themes as $theme) {
				if ($theme['status'] == 'active') {
					$active_theme = $theme['Text Domain'];
				}
			}
			$info_key = Customizer::where([
				['key', $request->main_id],
				['theme_name', $active_theme],
			])->first();

			if ($info_key) {
				$old_value = json_decode($info_key->value,true);
				$main = $request->id;
				if (!isset($old_value['settings'][$main])) {
					$data = [
							'old_value' => null,
							'new_value' => $request->value
					];
					$result = data_fill($old_value, 'settings.'.$request->id, $data);
				}else{
					$man = $old_value['settings'][$request->id];
					foreach ($old_value['settings'] as $key => $value) {
						$old_value['settings'][$request->id]['old_value'] =  $man['new_value'];
						$old_value['settings'][$request->id]['new_value'] =  $request->value;
					}
					$result = $old_value;
				}

				$info_key->value = json_encode($result);
				$info_key->status = 0;
				$info_key->save();
				return $info_key;
			}else{
				
				

				$a = [
					$request->id => [
						'old_value' => null,
						'new_value' => $request->value
					]
				];


				$data = [];

				$result = data_fill($data, 'settings', $a);

				$customizer = new Customizer();
				$customizer->key = $request->main_id;
				$customizer->theme_name = $active_theme;
				$customizer->value = json_encode($result);
				$customizer->status = 0;
				$customizer->save();
				return $customizer;

			}
		}
	}


	public function multiple_settings_option(Request $request)
	{

		if ($request->option == 'content') {
			$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
			$themes = json_decode($file, true);
			foreach ($themes as $theme) {
				if ($theme['status'] == 'active') {
					$active_theme = $theme['Text Domain'];
				}
			}
			$info_key = Customizer::where([
				['key', $request->main_id],
				['theme_name', $active_theme],
			])->first();

			if ($info_key) {
				$old_value = json_decode($info_key->value,true);
				$main = $request->p_id;
				if (!isset($old_value['content'][$main][$request->id])) {
					$data = [
							'old_value' => null,
							'new_value' => $request->value
					
					];

					 $result = data_fill($old_value, 'content.'.$main.'.'.$request->id, $data);
				}else{
					 $man = $old_value['content'][$request->p_id][$request->id];
					foreach ($old_value as $key => $value) {
						$old_value['content'][$request->p_id][$request->id]['old_value'] =  $man['new_value'];
						$old_value['content'][$request->p_id][$request->id]['new_value'] =  $request->value;
					}
					 $result = $old_value;
				}

				$info_key->value = json_encode($result);
				$info_key->status = 0;
				$info_key->save();
				return $info_key;
			}else{


				$a = [
					$request->p_id => [
						$request->id => [
							'old_value' => null,
							'new_value' => $request->value
						]
					]
				];


				$data = [];

				$result = data_fill($data, 'content', $a);
				$customizer = new Customizer();
				$customizer->key = $request->main_id;
				$customizer->theme_name = $active_theme;
				$customizer->value = json_encode($result);
				$customizer->status = 0;
				$customizer->save();
				return $customizer;

			}
		}
	}


	public function image_upload(Request $request)
	{
		
		$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
		$themes = json_decode($file, true);
		foreach ($themes as $theme) {
			if ($theme['status'] == 'active') {
				$active_theme_name = $theme['Text Domain'];
			}
		}

		$file = $request->file('img'.$request->id);
		if (isset($file)) {
			$curentdate = Carbon::now()->toDateString();
			$imagename =  $curentdate . '-' . uniqid() . '.' . $file->getClientOriginalExtension();


			$path = 'uploads/';

			$file->move($path, $imagename);

			$file_name = $path.$imagename;

			$main_file_path = 'uploads/'. $imagename;

			$media = new Media();
			$media->user_id = Auth::User()->id;
			$media->name = $path.$imagename;
			$media->type = $file->getClientOriginalExtension();
			$schemeurl=parse_url(url('/'));
            if ($schemeurl['scheme']=='https') {
               $url=substr(url('/'), 6);
            }
            else{
                 $url=substr(url('/'), 5);
            }
			$media->url = $url.'/'.$path.$imagename;
			$media->size = File::size('uploads/'.$imagename).'kib';
			$media->path = 'uploads/';
			$media->save();

		}else{
			$imagename = 'default.png';
		}

		

		if ($request->option == 'key') {
			$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
			$themes = json_decode($file, true);
			foreach ($themes as $theme) {
				if ($theme['status'] == 'active') {
					$active_theme = $theme['Text Domain'];
				}
			}
			$info_key = Customizer::where([
				['key', $request->main_id],
				['theme_name', $active_theme],
			])->first();

			if ($info_key) {
				$old_value = json_decode($info_key->value,true);
				$main = $request->id;
				if (!isset($old_value['settings'][$main])) {
					$data = [
							'old_value' => null,
							'new_value' => $main_file_path
					];
					$result = data_fill($old_value, 'settings.'.$request->id, $data);
				}else{
					$man = $old_value['settings'][$request->id];
					foreach ($old_value['settings'] as $key => $value) {
						$old_value['settings'][$request->id]['old_value'] =  $man['new_value'];
						$old_value['settings'][$request->id]['new_value'] =  $main_file_path;
					}
					$result = $old_value;
				}

				$info_key->value = json_encode($result);
				$info_key->status = 0;
				$info_key->save();
				return $info_key;
			}else{
				
				

				$a = [
					$request->id => [
						'old_value' => null,
						'new_value' => $main_file_path
					]
				];


				$data = [];

				$result = data_fill($data, 'settings', $a);

				$customizer = new Customizer();
				$customizer->key = $request->main_id;
				$customizer->theme_name = $active_theme;
				$customizer->value = json_encode($result);
				$customizer->status = 0;
				$customizer->save();
				return $customizer;

			}
		}


		if ($request->option == 'content') {
			$file = file_get_contents( base_path().'/am-content/Themes/theme.json');
			$themes = json_decode($file, true);
			foreach ($themes as $theme) {
				if ($theme['status'] == 'active') {
					$active_theme = $theme['Text Domain'];
				}
			}
			$info_key = Customizer::where([
				['key', $request->main_id],
				['theme_name', $active_theme],
			])->first();

			if ($info_key) {
				$old_value = json_decode($info_key->value,true);
				$main = $request->p_id;
				if (!isset($old_value['content'][$main][$request->id])) {
					$data = [
							'old_value' => null,
							'new_value' => $main_file_path
					
					];

					 $result = data_fill($old_value, 'content.'.$main.'.'.$request->id, $data);
				}else{
					 $man = $old_value['content'][$request->p_id][$request->id];
					foreach ($old_value as $key => $value) {
						$old_value['content'][$request->p_id][$request->id]['old_value'] =  $man['new_value'];

script/resources/views/admin/customizer/details.blade.php
<div class="loading">
    <div class="fusion-slider-loading">
    </div>
</div>  

<form action="{{ route('admin.customizer.image_upload') }}" id="img_form" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="header-top-info single_header d-flex">
        <span  onclick="arrow()" class="arrow_left"><i class="fas fa-chevron-left"></i></span>
        <span>{{ $option['name'] }}</span>
    </div>
    <input type="hidden" id="value_update" value="{{ route('admin.customizer.value_update') }}">
    <div class="main-sidebar-area">
        @if($option['settings'] != null)
        <div class="sidebar-header-title">
            <span>Settings</span>
        </div>

        <div class="custom-form">
            @foreach($option['settings'] as $settings)
            @if($settings['type'] == 'text')
            <div class="form-group">
                <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="settings_option('{{ $settings['id'] }}','text','key','{{ $option['id'] }}')" oninput="settings_option1('{{ $settings['id'] }}','text','key','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id']) }}">
            </div>
            @endif
            @if($settings['type'] == 'link')
            <div class="form-group">
                <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="settings_option('{{ $settings['id'] }}','link','key','{{ $option['id'] }}')" oninput="settings_option1('{{ $settings['id'] }}','link','key','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id']) }}">
            </div>
            @endif
            @if($settings['type'] == 'icon')
            <div class="form-group">
                <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="settings_option('{{ $settings['id'] }}','icon','key','{{ $option['id'] }}')" oninput="settings_option1('{{ $settings['id'] }}','icon','key','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id']) }}">
            </div>
            @endif
            @if($settings['type'] == 'textarea')
            <div class="form-group">
                <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                <textarea name="textarea" id="{{ $settings['id'] }}" cols="30" rows="5" class="form-control" onchange="settings_option('{{ $settings['id'] }}','text','key','{{ $option['id'] }}')" oninput="settings_option1('{{ $settings['id'] }}','textarea','key','{{ $option['id'] }}')">{{ content($option['id'],$settings['id']) }}</textarea>
            </div>
            @endif
            @if($settings['type'] == 'image')
            <div class="form-group imgUp">

                <label  for="{{ $settings['id'] }}">{{ $settings['label'] }}<br>

                    <div class="custom-image-area imagePreview" style="background-image: url({{ asset(content($option['id'],$settings['id'])) }});">

                        <div class="custom-img-info text-center">
                            <span>Select Image</span>
                        </div>
                    </div>
                </label>
                <input type="hidden" id="image_upload_url" value="{{ route('admin.customizer.image_upload',$settings['id']) }}">
                <input type="file" id="{{ $settings['id'] }}" name="img{{ $settings['id'] }}" class="uploadFile d-none" onchange="loadFile(event,'{{ $settings['id'] }}','image','key','{{ $option['id'] }}')">

            </div>
            @endif
             @if($settings['type'] == 'bg_image')
            <div class="form-group imgUp">

                <label  for="{{ $settings['id'] }}">{{ $settings['label'] }}<br>

                    <div class="custom-image-area imagePreview" style="background-image: url({{ asset(content($option['id'],$settings['id'])) }});">

                        <div class="custom-img-info text-center">
                            <span>Select Image</span>
                        </div>
                    </div>
                </label>
                <input type="hidden" id="image_upload_url" value="{{ route('admin.customizer.image_upload',$settings['id']) }}">
                <input type="file" id="{{ $settings['id'] }}" name="img{{ $settings['id'] }}" class="uploadFile d-none" onchange="loadFile(event,'{{ $settings['id'] }}','bg_image','key','{{ $option['id'] }}')">

            </div>
            @endif
            @endforeach

        </div>
        @endif
        @if($option['content'] != null)

        <div class="content-area">
            <div class="sidebar-header-title pb-15">
                <span>Content</span>
            </div>
            <div class="accordion" id="accordionExample">
                @foreach($option['content'] as $content)
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <a href="#" data-toggle="collapse" data-target="#{{ $content['id'] }}" aria-expanded="true" aria-controls="{{ $content['id'] }}">
                                <span class="flaticon-squares"></span> {{ $content['name'] }}
                            </a>
                        </h2>
                    </div>

                    <div id="{{ $content['id'] }}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="custom-form">
                                @foreach($content['settings'] as $settings)
                                @if($settings['type'] == 'text')
                                <div class="form-group">
                                    <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                                    <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="section_multi_options1('{{ $settings['id'] }}','text','content','{{ $option['id'] }}','{{ $content['id'] }}')" oninput="section_multi_options('{{ $settings['id'] }}','text','content','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id'],$content['id']) }}">
                                </div>
                                @endif
                                @if($settings['type'] == 'link')
                                <div class="form-group">
                                    <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                                    <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="section_multi_options1('{{ $settings['id'] }}','link','content','{{ $option['id'] }}')" oninput="section_multi_options('{{ $settings['id'] }}','link','content','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id'],$content['id']) }}">
                                </div>
                                @endif
                                @if($settings['type'] == 'icon')
                                <div class="form-group">
                                    <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                                    <input type="text" class="form-control" id="{{ $settings['id'] }}" onchange="section_multi_options1('{{ $settings['id'] }}','icon','content','{{ $option['id'] }}')" oninput="section_multi_options('{{ $settings['id'] }}','icon','content','{{ $option['id'] }}')" value="{{ content($option['id'],$settings['id'],$content['id']) }}">
                                </div>
                                @endif
                                @if($settings['type'] == 'image')
                                <div class="form-group imgUp">

                                    <label  for="{{ $settings['id'] }}">{{ $settings['label'] }}<br>

                                        <div class="custom-image-area imagePreview" style="background-image: url({{ asset(content($option['id'],$settings['id'],$content['id'])) }});">

                                            <div class="custom-img-info text-center">
                                                <span>Select Image</span>
                                            </div>
                                        </div>
                                    </label>
                                    <input type="hidden" id="image_upload_url" value="{{ route('admin.customizer.image_upload',$settings['id']) }}">
                                    <input type="file" id="{{ $settings['id'] }}" name="img{{ $settings['id'] }}" class="uploadFile d-none" onchange="loadFile(event,'{{ $settings['id'] }}','image','content','{{ $option['id'] }}','{{ $content['id'] }}')">

                                </div>
                                @endif

                                @if($settings['type'] == 'textarea')
                                <div class="form-group">
                                    <label for="{{ $settings['id'] }}">{{ $settings['label'] }}</label>
                                    <textarea name="textarea" id="{{ $settings['id'] }}" cols="30" rows="5" class="form-control" onchange="section_multi_options1('{{ $settings['id'] }}','text','content','{{ $option['id'] }}','{{ $content['id'] }}')" oninput="section_multi_options('{{ $settings['id'] }}','textarea','content','{{ $option['id'] }}')">{{ content($option['id'],$settings['id'],$content['id']) }}</textarea>
                                </div>
                                @endif
                                @endforeach
                                <input type="hidden" id="multiple_settings_option" value="{{ route('admin.customizer.multiple_settings_option') }}">
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            @endif
        </div>
    </div>
</form>